### ISSUE TITLE
Сode formatting

### ISSUE THREAD

**Issue by heX16** [ZiCog/mqtt-free-pascal#5]
the code has very non-standard formatting (strange string translations, large indents, spaces).
How about making _JEDI Code Formating_? (lazarus feature)
I can make Pull Request with new formating.

Example formating:

```
          constructor Create(Hostname: ansistring; Port: integer);
          overload;
          destructor Destroy;
          override;

   // Helper Function - Puts the seperate component together into an Array of Bytes for transmission
        function BuildCommand(FixedHead: Byte; RemainL: TRemainingLength; VariableHead: TBytes;
                              Payload:
                              array of Byte): TBytes; 
```

**Comment by lexbailey** [comment]
I realise that my opinion probably carries little weight in this context, as some random guy that once contributed to this a long while ago, but if you want my two pennies; formatting changes for the sake of formatting changes cause more problems than they solve. It makes git blame awkward, and makes merges or rebases hard.

These are unlikely to be issues on this project as there's probably not many [if any] people that will ever need to rebase or merge across a format change if you do it now. But you never know when it will suddenly pop up and cause problems.

**Comment by heX16** [comment]
I understand that it is difficult to merge two branches with different formatting.
But if all the branches (and all programmers write the new code) will do the JEDI Code Format then we will get the best indenticity of the code (and readability).
This will simplify the merger.

**Comment by ZiCog** [comment]
In general I'm not keen on code formatting changes, for these reasons discussed above.  However in this case it's not such a big project with not a lot of changes going on. And heX16 has been doing a lot of great work on it.

I'd be quite happy to accept a pull request that pulled the whole thing straight in one go. 

With one proviso. No TABs allowed!

**Comment by heX16** [comment]
https://github.com/ZiCog/mqtt-free-pascal/pull/6  Without a TAB! :-)

**Comment by ZiCog** [comment]
Excellent. Big thanks.
