### ISSUE TITLE
MQTT Username and Password support added.

### ISSUE THREAD

**Issue by ludoza** [ZiCog/mqtt-free-pascal#8]
Hi,

Been using the mqtt-free-pascal component recently to give my application message queue functionality and also sync with web apps.

But most brokers need a username and password. So I saw it was in the comments as a `TODO` item so I tried to hack in the functionality.

I commit the change to my own repository and the changeset can be found here:

https://github.com/ludoza/Chee/commit/af9ef37a5c126f27dcb626d16073befae663947f

If I must create a pull request or clean it up a bit before hand. Let me know, and I will try my best.

Thanks for the library!

**Comment by heX16** [comment]
Thank you very much for the work done!
Please do a pull request to my repository: https://github.com/heX16/mqtt-free-pascal

(Unfortunately, my code is a little different from this thread, so you have to merge)
